# Generated by Django 5.0.6 on 2024-07-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('M bags', 'M bags'), ('L bags', 'L bags'), ('S bags', 'S bags')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('M bags', 'M bags'), ('L bags', 'L bags'), ('S bags', 'S bags')], max_length=50),
        ),
    ]
