# Generated by Django 5.0.6 on 2024-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_category_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('S bags', 'S bags'), ('M bags', 'M bags'), ('L bags', 'L bags')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('S bags', 'S bags'), ('M bags', 'M bags'), ('L bags', 'L bags')], max_length=50),
        ),
    ]
