# Generated by Django 5.0.6 on 2024-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_category_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('M bags', 'M bags'), ('S bags', 'S bags'), ('L bags', 'L bags')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('M bags', 'M bags'), ('S bags', 'S bags'), ('L bags', 'L bags')], max_length=50),
        ),
    ]
