# Generated by Django 4.2 on 2024-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_category_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Cards', 'Cards'), ('Phone bag', 'Phone bag'), ('Classic', 'Classic'), ('Key chain', 'Key chain'), ('Accessories', 'Accessories'), ('Wood', 'Wood'), ('Mini', 'Mini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Cards', 'Cards'), ('Phone bag', 'Phone bag'), ('Classic', 'Classic'), ('Key chain', 'Key chain'), ('Accessories', 'Accessories'), ('Wood', 'Wood'), ('Mini', 'Mini')], max_length=50),
        ),
    ]
