# Generated by Django 5.0.6 on 2024-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_category_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Key chain', 'Key chain'), ('Wood', 'Wood'), ('Phone bag', 'Phone bag'), ('Classic', 'Classic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Key chain', 'Key chain'), ('Wood', 'Wood'), ('Phone bag', 'Phone bag'), ('Classic', 'Classic')], max_length=50),
        ),
    ]
