# Generated by Django 5.0.6 on 2024-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_category_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Phone bag', 'Phone bag'), ('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Wood', 'Wood'), ('Key chain', 'Key chain'), ('Mini', 'Mini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Phone bag', 'Phone bag'), ('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Wood', 'Wood'), ('Key chain', 'Key chain'), ('Mini', 'Mini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
