# Generated by Django 5.0.6 on 2024-07-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_category_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Classic', 'Classic'), ('Key Chain', 'Key Chain'), ('Phone Bag', 'Phone Bag'), ('Mini', 'Mini'), ('Wood', 'Wood'), ('Cards', 'Cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Classic', 'Classic'), ('Key Chain', 'Key Chain'), ('Phone Bag', 'Phone Bag'), ('Mini', 'Mini'), ('Wood', 'Wood'), ('Cards', 'Cards')], max_length=50),
        ),
    ]
