# Generated by Django 5.0.6 on 2024-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_category_alter_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Key Chain', 'Key Chain'), ('Classic', 'Classic'), ('Cards', 'Cards'), ('Phone Bag', 'Phone Bag'), ('Wood', 'Wood'), ('Accessories', 'Accessories'), ('Mini', 'Mini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Key Chain', 'Key Chain'), ('Classic', 'Classic'), ('Cards', 'Cards'), ('Phone Bag', 'Phone Bag'), ('Wood', 'Wood'), ('Accessories', 'Accessories'), ('Mini', 'Mini')], max_length=50),
        ),
    ]
