# Generated by Django 4.2 on 2024-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Phone Bag', 'Phone Bag'), ('Classic', 'Classic'), ('Wood', 'Wood'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Cards', 'Cards'), ('Key Chain', 'Key Chain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Phone Bag', 'Phone Bag'), ('Classic', 'Classic'), ('Wood', 'Wood'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Cards', 'Cards'), ('Key Chain', 'Key Chain')], max_length=50),
        ),
    ]
