# Generated by Django 4.2 on 2024-07-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_order_category_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Wood', 'Wood'), ('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Key Chain', 'Key Chain'), ('Phone Bag', 'Phone Bag')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Wood', 'Wood'), ('Cards', 'Cards'), ('Accessories', 'Accessories'), ('Mini', 'Mini'), ('Key Chain', 'Key Chain'), ('Phone Bag', 'Phone Bag')], max_length=50),
        ),
    ]
